In [8]:
import torch
import torch.nn.functional as F

a = torch.tensor([[1, 2, 3], [3, 4, 5]], dtype=torch.float)
b = torch.tensor([[5, 2, 3], [1, 4, 7]], dtype=torch.float)

a1 = F.normalize(a)
b1 = F.normalize(b)

In [11]:
c1 = torch.sum(a1 * b1, dim=1)

In [12]:
c1

tensor([0.7804, 0.9400])

In [9]:
a1

tensor([[0.2673, 0.5345, 0.8018],
        [0.4243, 0.5657, 0.7071]])

In [10]:
b1

tensor([[0.8111, 0.3244, 0.4867],
        [0.1231, 0.4924, 0.8616]])

In [13]:
torch.cosine_similarity(a, b, dim=1, eps=1e-08)

tensor([0.7804, 0.9400])